FROM python:3.11

ENV BACKEND_URL=http://host.docker.internal:8000/rag/query

WORKDIR /dashboard

COPY frontend/ /dashboard/


RUN pip install --no-cache-dir streamlit requests python-dotenv

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]